language: erlang
otp_release:
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02
notifications:
  email:
    recipients:
      - krzysztof.rutka@gmail.com
    on_success: never
    on_failure: always
